<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CU_btn-Send</name>
   <tag></tag>
   <elementGuidId>7512263b-5a5a-42d7-b9d5-55bc0ae45198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='send_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#send_btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'send_btn' and @type = 'button' and (text() = 'SEND' or . = 'SEND')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e3bf3c3-e6f3-4185-8a44-307eb9fc5684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send_btn</value>
      <webElementGuid>8adc1727-b80d-4e10-957b-02de60f2e270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b052a94-6954-4ccf-918a-142ff36bff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope invalid</value>
      <webElementGuid>9e15d486-8df0-4213-85ba-33802b872010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f4614fd-51fd-4fda-8294-11a010e2153e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>7237441a-4f2e-4bdd-9296-138189a3009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEND</value>
      <webElementGuid>5fd73c8d-869c-4442-ae9b-7ef9ee17759c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send_btn&quot;)</value>
      <webElementGuid>6bf669a9-baad-44ef-9ce0-e542bc28a4ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='send_btn']</value>
      <webElementGuid>80fc6481-fe1d-4549-a274-fe90fed829df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div[2]/div/sec-sender/button</value>
      <webElementGuid>5acd8157-d42c-41c1-af8d-43c443eb47f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email field is required'])[2]/following::button[1]</value>
      <webElementGuid>74982f45-c686-4368-848c-e9816efc7314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='subjectTextarea'])[1]/following::button[1]</value>
      <webElementGuid>2d847b91-3c67-4c28-8be9-c552621c6382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE SHOPPING'])[1]/preceding::button[1]</value>
      <webElementGuid>07bf719c-e0b3-4085-9041-c71a8fa6515e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FOLLOW US'])[1]/preceding::button[1]</value>
      <webElementGuid>53e29c7c-152f-47dc-9bf9-e031f52a5b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/sec-sender/button</value>
      <webElementGuid>c4fbbbe7-e776-4c8f-83ff-9026737febf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'send_btn' and @type = 'button' and (text() = 'SEND' or . = 'SEND')]</value>
      <webElementGuid>2031b2c9-5c14-4199-9db4-e7a2edad5460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
