<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SO_productCO-btn-colorPurple</name>
   <tag></tag>
   <elementGuidId>c1583f7c-45ad-4380-aecd-62b9d3e2074c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='bunny'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c12675fe-a0ef-46e8-ba48-c0acce27345a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PURPLE</value>
      <webElementGuid>2962e519-c1f5-463a-b26d-d8724cb4509b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bunny</value>
      <webElementGuid>25edee94-e911-43f1-9233-cf731cb02373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-repeat</name>
      <type>Main</type>
      <value>color in colors</value>
      <webElementGuid>32a37f39-234c-492f-bee5-23f3d6a33bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bunny productColor ng-scope PURPLE</value>
      <webElementGuid>16dcf1da-3272-41bb-bc79-d416cd321629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>color.code == 'ABCDEF'</value>
      <webElementGuid>fb642681-644d-4e84-abfa-9549e3b665ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-style</name>
      <type>Main</type>
      <value>color.code == 'FFFFFF' ?
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px #9d9d9d' } :
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px transparent'}</value>
      <webElementGuid>1a92bb9f-2f46-456f-8c54-92caaf7f0272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ colorSelected : colorSelected.name == color.name , PURPLE : colorSelected.name}</value>
      <webElementGuid>60a151ee-dd3f-4ff4-a508-5f91ebff32c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setColor(color, $event)</value>
      <webElementGuid>a6976b71-24b3-4afe-9841-c31ae51a0da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/div[2]/span[@id=&quot;bunny&quot;]</value>
      <webElementGuid>3c66cab6-c476-4789-8ea6-de2503670736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='bunny'])[4]</value>
      <webElementGuid>c0ee28e7-2fe6-4e71-9b8d-f41d494173e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/div[2]/span[4]</value>
      <webElementGuid>58e0587d-6715-4fb0-a279-62f75a60258c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::span[10]</value>
      <webElementGuid>4079a2bc-6bce-4c59-a335-9179232a05a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::span[10]</value>
      <webElementGuid>4aa8132b-40c0-4913-8bcb-6acf1f5a2fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::span[3]</value>
      <webElementGuid>deec1137-bed7-4272-bc9e-3bcd2fab3b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::span[3]</value>
      <webElementGuid>4d5fe25c-33e0-4ca6-a618-bb84f3acadeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[4]</value>
      <webElementGuid>97165564-f99a-4cb9-8dd9-0181580c936d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'PURPLE' and @id = 'bunny']</value>
      <webElementGuid>70ab5a7d-ffdc-4ac6-a398-791b53e31c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
