<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SO_product-img_Laptop HP</name>
   <tag></tag>
   <elementGuidId>fbd2f185-5198-4f3f-9730-b89608285e35</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img-special-offer']/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Special-offer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>140c3e29-1ee3-40dd-8a81-3b42614d23ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/Special-offer.jpg</value>
      <webElementGuid>57f5fa37-02a3-4b4f-a666-39da896e9ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Special-offer</value>
      <webElementGuid>36d32a3e-bb33-4d58-9b34-77685859cc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-special-offer&quot;)/figure[1]/img[1]</value>
      <webElementGuid>e5d1459a-3a03-460a-bf00-581b4d18444b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-special-offer']/figure/img</value>
      <webElementGuid>63a51b33-2064-4b31-9813-0488dc928893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Special-offer']</value>
      <webElementGuid>4893ce91-5110-431d-98d1-ea217382a18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>e70e39a5-d16b-46b7-b115-03d593bd8aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'css/images/Special-offer.jpg' and @alt = 'Special-offer']</value>
      <webElementGuid>cfb6b932-7779-4655-b02b-790e9f8b7fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
