<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SO_productCO-btn-colorBlack</name>
   <tag></tag>
   <elementGuidId>fa8c8ae9-8ef6-456f-b53b-9e52a298d126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='bunny'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb2ae72b-4edd-4a59-afb0-2f3a2f7fba43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BLACK</value>
      <webElementGuid>573469bd-6266-46fb-8bbb-a249508d8fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bunny</value>
      <webElementGuid>b188a812-cab3-4195-85b5-3b90f77ecb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-repeat</name>
      <type>Main</type>
      <value>color in colors</value>
      <webElementGuid>5bb6588a-390f-423b-8b94-315c1b1609d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bunny productColor ng-scope BLACK</value>
      <webElementGuid>a7e5da38-b2ae-4e1c-9d02-0a986164b3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>color.code == 'ABCDEF'</value>
      <webElementGuid>42c50661-d80b-4f69-ad0a-2971f2a266f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-style</name>
      <type>Main</type>
      <value>color.code == 'FFFFFF' ?
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px #9d9d9d' } :
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px transparent'}</value>
      <webElementGuid>ce9cb6be-4dd5-40fb-b65f-d606cf418553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ colorSelected : colorSelected.name == color.name , BLACK : colorSelected.name}</value>
      <webElementGuid>ef6c56b3-dd70-41ee-a3dd-64194e8a155e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setColor(color, $event)</value>
      <webElementGuid>18d434bf-81ce-4baa-a9d6-c09999f033a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/div[2]/span[@id=&quot;bunny&quot;]</value>
      <webElementGuid>91995e1d-3dba-4c55-910c-543f27e91fb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='bunny'])[2]</value>
      <webElementGuid>b036a18f-1a7e-4ab2-b71f-72ab2cad0f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/div[2]/span[2]</value>
      <webElementGuid>b349c8b8-3409-4e31-a80f-418b97217b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::span[8]</value>
      <webElementGuid>56643517-15bb-4278-a6a1-92909a64fae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::span[8]</value>
      <webElementGuid>be797086-1fbe-477b-8c96-7e91140afd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::span[5]</value>
      <webElementGuid>9c994677-3478-4134-b2c7-ffb7a427cd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::span[5]</value>
      <webElementGuid>7e966b49-1b3d-4102-bf25-3383d2887289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>5ec05830-8e95-4f65-b1e9-200882fccd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'BLACK' and @id = 'bunny']</value>
      <webElementGuid>89b6fc59-9658-4695-859e-706d3139783b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
