<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SP_list-titile-CATEGORIES</name>
   <tag></tag>
   <elementGuidId>b8324f03-730b-4c8f-9db6-8535f5375e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='output']/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.roboto-medium.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>d733d1e4-f801-4203-b5af-d9e27e744faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-scope</value>
      <webElementGuid>536ca91c-17a9-4b24-92a6-724823a16ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>CATEGORIES</value>
      <webElementGuid>941ecefd-4725-4876-9ce7-18286a94a84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-mouseenter</name>
      <type>Main</type>
      <value>searchByCategoryId(null, '')</value>
      <webElementGuid>4db3f7a0-0487-44ee-9155-b16000964f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CATEGORIES</value>
      <webElementGuid>fad5d59a-9767-4d5e-8582-e6d4f56af8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;output&quot;)/div[@class=&quot;searchPopUp&quot;]/div[@class=&quot;categories&quot;]/h3[@class=&quot;roboto-medium ng-scope&quot;]</value>
      <webElementGuid>e60fd741-b25d-4ba4-8b72-72a2812b0efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/div/h3</value>
      <webElementGuid>1ff1b583-0e2d-44d6-8c69-b8162f6bef58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[2]/following::h3[1]</value>
      <webElementGuid>e37efe56-8845-400b-b34c-65a25ef609b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/following::h3[1]</value>
      <webElementGuid>bd818eae-c432-4568-9b26-47abd4fb5b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='headphones'])[1]/preceding::h3[1]</value>
      <webElementGuid>45b3a0f0-f24b-4629-958b-05f3d808a05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('TOP RESULTS FOR: ', '&quot;', 'headphone', '&quot;', '')])[1]/preceding::h3[1]</value>
      <webElementGuid>2c0e7321-2f73-430f-98f6-7c0d1570a520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>e44f6230-8aef-4c2c-bbbf-de1368744c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'CATEGORIES' or . = 'CATEGORIES')]</value>
      <webElementGuid>29f37874-d202-46fe-a1ff-1c34cc40a0fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
