<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SP_productCO-btn-ifMore1-QuantityMinusDisabled</name>
   <tag></tag>
   <elementGuidId>b35fb470-7af1-4420-993b-d685c82970cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.minus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>adba8de6-3dfe-4172-8d90-e90cb2910fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minus</value>
      <webElementGuid>4dbbe611-8b46-4eed-ac39-7e89263e10a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>increment-value-attr</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>0c24a839-aece-4999-969a-3a9213e15363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;smoolMargin&quot;]/e-sec-plus-minus[@class=&quot;ng-isolate-scope sec-plus-minus&quot;]/div[@class=&quot;e-sec-plus-minus&quot;]/div[@class=&quot;minus&quot;]</value>
      <webElementGuid>4b7f64ad-f447-4893-bb9c-de23acae2079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div</value>
      <webElementGuid>f87b9307-e892-4cb2-9c0b-8007a82d8ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//e-sec-plus-minus/div/div</value>
      <webElementGuid>ee98ed6a-8f1e-41f5-87dc-1595fac7c843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
