<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SP_productCO-nameProduct-Beats Studio</name>
   <tag></tag>
   <elementGuidId>b7892b50-8918-4671-8ad9-5266895f807b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Description']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.roboto-regular.screen768.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>bafbbd71-cb51-4e6e-9197-213db6b489c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular screen768 ng-binding</value>
      <webElementGuid>13391bbc-48b4-4931-95c4-40c8cc770984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BEATS STUDIO 2 OVER-EAR MATTE BLACK HEADPHONES </value>
      <webElementGuid>6bdf9984-9237-4e2d-b70e-d6d97fbd9412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)/h1[@class=&quot;roboto-regular screen768 ng-binding&quot;]</value>
      <webElementGuid>7ff9f4fb-82f5-4b8a-a424-d4459c2a0613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Description']/h1</value>
      <webElementGuid>824489fe-cd09-45a1-8d20-f5dbfacadc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[1]/following::h1[1]</value>
      <webElementGuid>e46bf16a-0a06-4ff6-a22d-fff0281e1784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/preceding::h1[1]</value>
      <webElementGuid>78264faa-e119-4716-a2d5-c85eb2a56e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>a8645b3f-0589-41ff-9292-ea584b0d9e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = ' BEATS STUDIO 2 OVER-EAR MATTE BLACK HEADPHONES ' or . = ' BEATS STUDIO 2 OVER-EAR MATTE BLACK HEADPHONES ')]</value>
      <webElementGuid>7a4d0008-07f0-49da-9ec0-3c5b5e1caf5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
