<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SP_productCO-btn-QuantityPlus</name>
   <tag></tag>
   <elementGuidId>c13afbb8-049b-49fe-abe1-738011bb611e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.plus</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;productProperties&quot;)/div[@class=&quot;smoolMargin&quot;]/e-sec-plus-minus[@class=&quot;ng-isolate-scope sec-plus-minus&quot;]/div[@class=&quot;e-sec-plus-minus&quot;]/div[@class=&quot;plus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe7e2429-dd10-4d2e-8602-11b8192c2060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>fef0a95e-34ea-4648-8360-cd66bf9faec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>increment-value-attr</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>8fea962d-4cb7-48d6-802a-2ef54bd0afe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;smoolMargin&quot;]/e-sec-plus-minus[@class=&quot;ng-isolate-scope sec-plus-minus&quot;]/div[@class=&quot;e-sec-plus-minus&quot;]/div[@class=&quot;plus&quot;]</value>
      <webElementGuid>6ddb794d-ab52-4220-9767-48d0265212f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div[3]</value>
      <webElementGuid>72478752-ca3d-46e6-9e7c-4fc4e52ca13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//e-sec-plus-minus/div/div[3]</value>
      <webElementGuid>53450927-32dc-466c-8500-0e8aad116220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
